version: '3.8'

services:
  pg-database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres

  dbeaver-server:
    container_name: dbeaver-server
    depends_on:
      - pg-database
    image: dbeaver/cloudbeaver
    ports:
      - 7777:8978

  api:
    depends_on:
      - pg-database
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
    env_file:
      - .env
