services:
  pg-database:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
      - PGDATA=/data/postgres
    volumes:
      - ./data/pg:/data/postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  dbeaver-server:
    container_name: dbeaver-server
    depends_on:
      pg-database:
        condition: service_healthy
    image: dbeaver/cloudbeaver
    ports:
      - 7777:8978

  api:
    depends_on:
      pg-database:
        condition: service_healthy
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 4000:4000
      - 9229:9229
    env_file:
      - .env
    volumes:
      - .:/app
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'if [ $(curl -s -o /dev/null -w ''%{http_code}'' ${API_DOMAIN}:${API_PORT}/health) -ne 200 ]; then echo "Health check failed" >&2; exit 1; fi',
        ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
